name: TritonBench Compile Time Benchmark
on:
  schedule:
    # Test nightly docker daily at 4 PM UTC
    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        required: true
        description: 'Choose advanced testing options'
        default: 'single'
        options:
          - 'single'
          - 'abtest'
      side_a_triton:
        default: 'triton-lang/triton'
        description: 'Side A Triton repo'
      side_a_commit:
        default: 'main'
        description: 'Side A Triton commit'
      side_b_triton:
        default: 'triton-lang/triton'
        description: 'Side B Triton repo (abtest only)'
      side_b_commit:
        default: 'main'
        description: 'Side B Triton commit (abtest only)'
  pull_request:
    paths:
      - benchmarks/compile_time/**
      - .github/workflows/_linux-benchmark-*.yml
      - .github/workflows/compile-time.yml

jobs:
  h100-triton-main-compile_time-benchmark:
    uses: ./.github/workflows/_linux-benchmark-h100.yml
    with:
      test_type: ${{ inputs.test_type || 'periodic' }}
      benchmark_name: "compile_time"
      venv_name: "triton-main"
      side_a_triton: ${{ inputs.side_a_triton }}
      side_a_commit: ${{ inputs.side_a_commit }}
      side_b_triton: ${{ inputs.side_b_triton }}
      side_b_commit: ${{ inputs.side_b_commit }}
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}
  mi350-triton-main-compile_time-benchmark:
    uses: ./.github/workflows/_linux-benchmark-mi350.yml
    with:
      test_type: ${{ inputs.test_type || 'periodic' }}
      benchmark_name: "compile_time"
      venv_name: "triton-main"
      side_a_triton: ${{ inputs.side_a_triton }}
      side_a_commit: ${{ inputs.side_a_commit }}
      side_b_triton: ${{ inputs.side_b_triton }}
      side_b_commit: ${{ inputs.side_b_commit }}
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
