name: TritonBench TLX Benchmark
on:
  schedule:
    # Test daily at 4 PM UTC
    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        type: choice
        required: true
        description: 'Choose advanced testing options'
        default: 'single'
        options:
          - 'single'
          - 'abtest'
      side_a_triton:
        default: 'facebookexperimental/triton'
        description: 'Side A Triton repo'
      side_a_commit:
        default: 'main'
        description: 'Side A Triton commit'
      side_b_triton:
        default: 'facebookexperimental/triton'
        description: 'Side B Triton repo (abtest only)'
      side_b_commit:
        default: 'main'
        description: 'Side B Triton commit (abtest only)'
  pull_request:
    paths:
      - benchmarks/tlx/**
      - .github/workflows/_linux-benchmark-*.yml
      - .github/workflows/tlx.yml

jobs:
  h100-meta-triton-tlx-benchmark:
    uses: ./.github/workflows/_linux-benchmark-h100.yml
    if: ${{ inputs.test_type != 'abtest' }}
    with:
      test_type: ${{ inputs.test_type || 'periodic' }}
      benchmark_name: "tlx"
      venv_name: "meta-triton"
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
